version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: always

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    restart: always

  ept:
    build: ./event_prediction_EPT
    container_name: event_prediction_ept
    depends_on:
      - kafka
    restart: on-failure

  lfr:
    build: ./event_prediction_LFR
    container_name: event_prediction_lfr
    depends_on:
      - kafka
    restart: on-failure

  esm:
    build: ./event_prediction_ESM
    container_name: event_prediction_esm
    depends_on:
      - kafka
    restart: on-failure

  ranking_model:
    build: ./event_prediction_RM
    container_name: event_prediction_rm
    depends_on:
      - kafka
    restart: on-failure

  collector:
    build: ./event_prediction_collector
    container_name: event_prediction_collector
    depends_on:
      - kafka
    restart: on-failure

  event_specialist:
    build: ./event_prediction_LLM
    container_name: event_prediction_llm
    depends_on:
      - kafka
    restart: on-failure

  models_manager:
    build: ./event_prediction_models_manager
    container_name: event_prediction_models_manager
    depends_on:
      - kafka
    restart: on-failure
